# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: "/webapp/wiremock"
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    assignees:
      - Author
    versioning-strategy: increase
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "major"
        - "minor"
        - "patch"
      fortawesome:
        patterns:
        - "@fortawesome"
        update-types:
        - "major"
        - "minor"
        - "patch"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    assignees:
      - Author
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: docker
    directory: "/alpine"
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    assignees:
      - Author
    commit-message:
      prefix: "chore(deps)"
